# Generated by Django 4.2.5 on 2023-09-30 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dental_disease',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
