# Generated by Django 4.2.5 on 2023-09-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_user_birthday_user_dental_disease_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dental_disease',
            field=models.CharField(choices=[('D', 'Dental caries'), ('P', 'Periodonitis'), ('G', 'Gingivitis')], default='D', max_length=100),
        ),
    ]
